name: face_segmentation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=24.2
  - numpy=2.1.1
  - matplotlib=3.9.2
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.4
  - opencv=4.10.0
  - pip:
    - deepface==0.0.93
    - tf-keras==2.17.0